#!/usr/bin/perl
use strict;
use warnings;
use Gtk3 -init;
use Getopt::Long;

use Gtk3::SourceEditor;

# --- CLI Argument Parsing ---
my $config_file = '';
my $theme_name = 'default';
my $read_only = 0;
my $font_size = 0;
my $wrap_enabled = 1;
my $no_line_numbers = 0;
my $block_cursor = 0;
my $highlight_current_line = 1;
my $filename = '';
my $help = 0;

GetOptions(
    'config|C=s'               => \$config_file,
    'theme=s'                   => \$theme_name,
    'read-only|r'               => \$read_only,
    'font-size|f=i'             => \$font_size,
    'wrap|w!'                   => \$wrap_enabled,
    'no-line-numbers|n'         => \$no_line_numbers,
    'cursor-block|b'            => \$block_cursor,
    'highlight-current-line|H!' => \$highlight_current_line,
    'help|h'                    => \$help,
);

if ($help) {
    print <<"USAGE";
Usage: source-editor [OPTIONS] [FILE]

Options:
  -C, --config=FILE            Load settings from a configuration file
                                (see editor.conf for format and available keys)
  -t, --theme=NAME             Theme name (default, dark, light, solarized)
  -r, --read-only              Open file in read-only mode
  -f, --font-size=N            Set font point size
  -w, --[no-]wrap              Enable/disable word wrap (default: on)
  -n, --no-line-numbers        Hide line number gutter
  -b, --cursor-block           Start with block cursor (instead of i-beam)
  -H, --[no-]highlight-current-line
                                Highlight current line (default: on)
  -h, --help                   Show this help message

Configuration file settings are used as defaults.  Command-line options
override the corresponding config file values.

The editor provides Vim-like modal keybindings.  Use :q to quit,
:w to save, :wq to save and quit, i/a/o to enter insert mode.
Press Escape to return to normal mode.
USAGE
    exit 0;
}

$filename = $ARGV[0] if @ARGV;

my $theme_file = $theme_name ne 'default' ? "themes/theme_$theme_name.xml" : 'themes/default.xml';

# --- Build Window ---
my $window = Gtk3::Window->new('toplevel');
$window->set_title($filename || "New File");
$window->set_default_size(800, 600);
$window->signal_connect(delete_event => sub { Gtk3->main_quit(); });

# --- Build editor options hash ---
my %editor_opts = (
    file                    => $filename,
    theme_file              => $theme_file,
    font_size               => $font_size,
    wrap                    => $wrap_enabled,
    read_only               => $read_only,
    show_line_numbers       => !$no_line_numbers,
    block_cursor            => $block_cursor,
    highlight_current_line  => $highlight_current_line,
    window                  => $window,
    on_close                => sub {
        my $final_text = shift;
        print "--- WINDOW CLOSED ---\nCaptured Text:\n$final_text\n";
    },
);

# Config file is passed through; SourceEditor merges it with lower priority.
$editor_opts{config_file} = $config_file if $config_file && -f $config_file;

# --- Instantiate Editor Module ---
my $editor = Gtk3::SourceEditor->new(%editor_opts);

# Pack the editor widget into the window and run
$window->add($editor->get_widget());
$window->show_all();
Gtk3->main();
