[book]
title = "P5-Gtk3-SourceEditor Documentation"
authors = ["nkh"]
language = "en"
src = "src"

# [build]
# build-dir = "book"

# [output]
# html.search.enabled = true
# html.print-page.enabled = false

# [output.html.fold]
# enable = true
# level = 0
